### PR TITLE
Update redirects using netlify.toml [Closes #562]

### LINKED ISSUE #562: Add redirect for old Merge Readiness page
Found a broken link to:
https://launchpad.ethereum.org/en/merge-readiness

Let's add a redirect (for all languages) to the corresponding Checklist:
https://launchpad.ethereum.org/en/checklist

### PR DESCRIPTION
**Pull request by wackerow**
### Description
- Adds redirect from recently deprecated `merge-readiness` page to `checklist` page using `/public/_redirects`

### Related issues
- Closes #562

### CODE REVIEW

**Comment by samajammin** [comment]
Thanks for hopping on this @wackerow!

Doesn't seem to be working for me: https://deploy-preview-563--serene-carson-3331d5.netlify.app/en/merge-readiness
(I'm guessing why it's still in draft)

Also noting this is meant to address #562 - please remember to link the issue 😄

**Comment by wackerow** [comment]
Yea, draft mode for now while getting Netlify access to make it easier. Will add closing tag for issue

**Comment by samajammin** [comment]
Any progress on this @wackerow?

**Comment by wackerow** [comment]
Should be good to go now

**Review by samajammin — APPROVED** [review]
👍

**Pull request merged**
