### PR TITLE
Adds Lodestar support

### PR DESCRIPTION
**Pull request by CarlBeek**
Now that Lodestar [has released](https://github.com/ChainSafe/lodestar/releases/tag/v1.0.0) `v1.0.0`, this PR re-implements #436 just on-top of a fresher branch of `dev`.

### CODE REVIEW

**Comment by wackerow** [comment]
(Awaiting a patch release for necessary fixes first from Lodestar team)

**Comment by wackerow** [comment]
Just pinged on #436 as well, but I'll ask over here as well.. @CarlBeek have you heard any word on this?

**Comment by wackerow** [comment]
Just closed #436 in favor of this PR given additional link fixes, and merge conflicts cleared. See that PR for existing conversation.

@philknows Please drop a note here when Lodestar is ready 🙏  Thanks!

**Comment by philknows** [comment]
Hey @wackerow, released v1.4.0 today. Blog post coming out shortly with announcement. Ready when you are! Thanks for this!

**Review by q9f — APPROVED** [review]

**Review by wackerow — APPROVED** [review]
https://blog.chainsafe.io/lodestar-v1-4-0-release-and-a-look-ahead-8f0a99c2e708
🎉

**Pull request merged**
