### PR TITLE
add lodestar

### PR DESCRIPTION
**Pull request by skylenet**
Solves https://github.com/ethereum/staking-launchpad/issues/430  and https://github.com/ChainSafe/lodestar/issues/3008

### CODE REVIEW

**Review by CarlBeek — COMMENTED** [review]
I definitely like the direction this is going, definitely keen to get Lodestar up there.

Having had some internal discussions, we've decided to hold off on merging this for a while until we are absolutely convinced Lodestar is mainnet ready from a reliability & safety standpoint. By including a client on the launchpad, we are effectively endorsing them as a not-too-risky choice, and I'm just not prepared to make that determination yet.

Let's see how the new Prater Lodestar nodes do along with the mainnet ones (there are 2 I am aware of) and circle back after a while.

**Comment by skylenet** [comment]
Thanks for the review @CarlBeek . I've updated the descriptions based on your feedback.

One thing that could be done, is to make it configurable via an env var (e.g. `REACT_APP_CLIENTS_LODESTAR_ENABLED`).
That way we could have different configurations for each envionment. Mainnet would have that set to 'false', but Prater could have it set to 'true'. 

What do you think?

**Comment by philknows** [comment]
> I definitely like the direction this is going, definitely keen to get Lodestar up there.
> 
> Having had some internal discussions, we've decided to hold off on merging this for a while until we are absolutely convinced Lodestar is mainnet ready from a reliability & safety standpoint. By including a client on the launchpad, we are effectively endorsing them as a not-too-risky choice, and I'm just not prepared to make that determination yet.
> 
> Let's see how the new Prater Lodestar nodes do along with the mainnet ones (there are 2 I am aware of) and circle back after a while.

Hey @CarlBeek , thanks for this. We can keep you updated and discuss what other blockers to remove and milestones we can try to achieve before you decide to merge this in. I'm on the ethereum.org and ChainSafe discord servers as phil.knows#8609

**Comment by philknows** [comment]
Hi @CarlBeek, just an update on our side, we've implemented a production release track into Lodestar and have been running multiple mainnet validators through the Ethereum Client Incentive Program since mid-December. Feel free to reach out if you need any other specific milestones you'd like us to reach to merge this in. Thanks!

**Comment by wackerow** [comment]
Hey @skylenet! Sounds like this is still temporarily on hold, so I just flipped this to draft mode for the time being. In the meantime I updated with the merge conflicts cleaned up.

**Comment by philknows** [comment]
Hey @CarlBeek @skylenet @wackerow, I just wanted to revisit this PR to get an idea of your perspective of what needs to be met for this to be merged. I believe that part of the reason why we're still struggling to see usage here is our lack of visibility in some important parts of the Ethereum ecosystem such as the staking launchpad. Although it is quite clear that people within the protocol community are well aware of 5 functioning consensus clients through our participation in major events such as the shadow forks of which we have had no large participation issues.

Some presentations at DevConnect consistently mention 5 consensus clients, including @djrtwo's presentation at EthStaker which included a screengrab of our logo because this PR was not merged. The Ethereum Foundation's report released on Apr 18 mentions 5 consensus clients ready for the merge and talks which included consensus clients always included Lodestar in some way, including the Secureum TrustX Deep Dive with consensus client teams. In addition, we have an upcoming audit in preparation of our v1.0.0 release scheduled this summer.

I would be happy to provide you with some metrics of our client on mainnet and discuss further in detail if there are any additional hesitations with pushing us up to production status & getting this merged.

**Comment by fredriksvantes** [comment]
Hello! The current status for this is that a third party audit on Lodestar is starting this week, and this will be completed towards the mid-end of July. Once this has been completed, the intention is to add Lodestar on the same locations as the other clients on ethereum.org and the launchpad.

**Comment by SeaMonkey82** [comment]
Any update on this?

**Comment by philknows** [comment]
Hey @SeaMonkey82 , we're currently implementing fixes from the audit. They will get implemented in a future release and we'll do an announcement upon its completion. Shortly after that, we will give some time for users to upgrade and Lodestar will get listed, which includes this PR.

**Comment by wackerow** [comment]
Hey @philknows/@skylenet... any update here?

**Comment by philknows** [comment]
Hey @wackerow, we're targeting a v1.4.0 release for EF endorsement which would upgrade some of the dependencies for fixes to currently disclosed public vulnerabilities alongside the audit fixes. We decided to take a more conservative approach to address all publicly open eth client vulnerabilities before getting listed on the launchpad. Targeting Q1 2023 ideally before withdrawals are enabled. 🤞

**Comment by philknows** [comment]
Hey everyone, quick update here our own status with closing up security vulnerabilities and the audit. Our [next release `v1.4.0-rc.0`](https://github.com/ChainSafe/lodestar/releases/tag/v1.4.0-rc.0)  is in release candidate testing phase and will include all the fixes to satisfy the audit and other known vulnerabilities. 

Hoping we can merge this very soon!

**Comment by wackerow** [comment]
Awesome, thanks @philknows for the update!

Noting that this PR ended up being duplicated on #541, which appears to have branched off this and fixed a link or two.

I'm going to close this PR in favor of the updated one, please do me a favor and comment on #541 when this is ready 🙏  Thanks!

**Pull request closed without merging**
