### PR TITLE
Adding Wagyu Key Gen option to the generating keys section

### LINKED ISSUE #460: Add Wagyu Key Gen app to Generate key section
[Wagyu Key Gen](https://github.com/stake-house/wagyu-key-gen) is a GUI wrapper on top of staking-deposit-cli (previously known as eth2.0-deposit-cli) to generate your keys. It was fully audited. It works well on Linux, Windows and Mac.

We could do the PR to include this if adding this tool is fine with you.

### PR DESCRIPTION
**Pull request by remyroy**
This PR adds the Wagyu Key Gen option to the generating keys section. [Wagyu Key Gen](https://github.com/stake-house/wagyu-key-gen) is a GUI wrapper on top of staking-deposit-cli (previously known as eth2.0-deposit-cli) to generate your keys. It was fully audited. It works well on Linux, Windows and Mac.

Closes #460

### CODE REVIEW

**Review by wackerow — COMMENTED** [review]
@remyroy This looks great! Appreciate you putting this together, and was very in line with how I was thinking about pulling this in. 

The only thought I had was wondering if we should link out to the audit as well, for those looking for security reassurances.

Maybe something like this:
image

Otherwise looking forward to pulling this in =)

**Comment by remyroy** [comment]
I would be happy to add that link to our audit report. I should be able to add it on Monday.

**Comment by remyroy** [comment]
@wackerow I've added the link to the Wagyu Key Gen audit.

**Review by wackerow — APPROVED** [review]
Lookin good to me, thanks @remyroy!

**Pull request merged**
