### PR TITLE
Bump web3.js to v1.7.5

### PR DESCRIPTION
**Pull request by hwwhww**
To fix the recent Brave browser issue, this PR bumps web3.js package version to `v1.7.5`.

TODO:
- [x] Test deposit function

### CODE REVIEW

**Comment by hwwhww** [comment]
Hey @samajammin @wackerow 
This PR works for me locally. But somehow Netlify didn't install successfully.

Newbie question: I clicked the "Re-run" button of one failed check and then saw "You have successfully requested Header rules - serene-carson-3331d5 be rerun":
image

But I couldn't find the re-run. Any idea of how to resolve it?

**Comment by wackerow** [comment]
@hwwhww This appears to be a Node JS version issue... 
```log
1:18:32 AM: error got@12.1.0: The engine "node" is incompatible with this module. Expected version ">=14.16". Got "10.24.1"
1:18:32 AM: error Found incompatible module.
```

We appear to be using `10.24.1 (lts/dubnium)` while this is requiring `>=14.16 (lts/fermium)`.

@CarlBeek Have we looked into updating the node version in the past? Any idea if that would affect anything else on the site? I generally use `lts/gallium -> v16.17.0` as my default, and locally the site has always worked, and this PR also works fine if using that version, but breaks as soon as I switch to `10.24.1`

**Comment by CarlBeek** [comment]
In general, updating the packages would be good. I made an attempt in the past to update everything to the latest stable versions and then lost a day to dependency hell trying to figure out what was and wasn't working. That said, this is probably more a fault of my JS skills than anything else.

**Comment by hwwhww** [comment]
@wackerow I rebased this PR with #546 changes, it works now! 🎉

**Review by wackerow — APPROVED** [review]

**Comment by meshin-blox** [comment]
Guys please merge it as soon as possible

**Comment by meshin-blox** [comment]
What is the status of this?

**Review by wackerow — APPROVED** [review]

**Pull request merged**
